baseURL = "https://Bladi-Yeager.github.io/"
title = "Blog de Bladi"
theme = "flat"

[author]
  name = "Bladi Yeager"
  email = "tucorreo@gmail.com"

[params]
  description = "Blog sobre Linux y tecnologia"