baseURL = "https://Bladi-Yeager.github.io/"
title = "Blog de Bladi"
theme = "flat"

[author]
  name = "Bladi Yeager"

[params]
  description = "Blog sobre Linux y tecnologia"
  customCSS = ["custom.css"]