baseURL = "https://Bladi-Yeager.github.io/"
locale = "es-419"
title = "Mi Blog"
theme = "flat"

[author]
  name = "SORIA"
  email = "bladimirsoriahinojosa8@email.com"

[params]
  description = "Mi blog personal"